### ISSUE TITLE
Runtime Error in Katacoda lesson

### ISSUE THREAD

**Issue by reselbob** [derberg/asyncapi-interactive-docs#2]
Here: `https://www.katacoda.com/asyncapi/scenarios/streetlight-tut`

Step 2: this command, `ag asyncapi.yaml @asyncapi/nodejs-template -o output -p server=mosquitto`

I am attaching a screenshot of this error.

If the cause of the error is due to a mistake on my end, please forgive me.

![Screen Shot 2020-10-22 at 10 55 50 AM](https://user-images.githubusercontent.com/1110569/96924556-aa859400-1467-11eb-88ef-13954e929435.png)

**Comment by derberg** [comment]
@reselbob Hey, thanks for reporting it. It fails as you did not follow the first step of the tutorial, where you have to create an asyncapi file first

<img width="487" alt="Screenshot 2020-10-22 at 22 31 48" src="https://user-images.githubusercontent.com/6995927/96926832-67064680-14b6-11eb-9c9a-624e7ded179b.png">

Please notice **copy to editor** button

**Comment by reselbob** [comment]
The mistake was mine. Please forgive me.

**Comment by derberg** [comment]
@reselbob no worries, it is always better to report than assume there is no problem. Thanks for taking the time.
